-- ============================================================
-- GBC Work Hub — 원격 PC 중앙 상태 공유 (Oracle)
-- DBA 실행용. 앱에 비밀번호를 넣지 마십시오.
-- ============================================================

-- 1) Sequences
CREATE SEQUENCE SEQ_GBC_REMOTE_PC
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

CREATE SEQUENCE SEQ_GBC_RDP_USAGE_LOG
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

-- 2) GBC_REMOTE_PC — 원격 PC 현재 상태 (1행/PC)
CREATE TABLE GBC_REMOTE_PC (
    REMOTE_PC_ID              NUMBER          NOT NULL,
    COMPUTER_NAME             VARCHAR2(100)   NOT NULL,
    IP_ADDRESS                VARCHAR2(50)    NOT NULL,
    DISPLAY_NAME              VARCHAR2(200),
    CURRENT_STATUS            VARCHAR2(30)    NOT NULL,
    CURRENT_SESSION_TOKEN     VARCHAR2(50),
    CURRENT_USER_ACCOUNT      VARCHAR2(200),
    CURRENT_CLIENT_PC         VARCHAR2(100),
    CONNECTION_REQUESTED_AT   TIMESTAMP,
    CONNECTION_CONFIRMED_AT   TIMESTAMP,
    LAST_HEARTBEAT_AT         TIMESTAMP,
    UPDATED_AT                TIMESTAMP       NOT NULL,
    VERSION_NO                NUMBER          DEFAULT 0 NOT NULL,
    IS_ACTIVE                 CHAR(1)         DEFAULT 'Y' NOT NULL,
    CONSTRAINT PK_GBC_REMOTE_PC PRIMARY KEY (REMOTE_PC_ID),
    CONSTRAINT UK_GBC_REMOTE_PC_NAME UNIQUE (COMPUTER_NAME),
    CONSTRAINT CK_GBC_REMOTE_PC_STATUS CHECK (
        CURRENT_STATUS IN ('AVAILABLE', 'CONNECTING', 'IN_USE', 'CHECK_REQUIRED')
    ),
    CONSTRAINT CK_GBC_REMOTE_PC_ACTIVE CHECK (IS_ACTIVE IN ('Y', 'N'))
);

-- 3) GBC_RDP_USAGE_LOG — 접속 이력
CREATE TABLE GBC_RDP_USAGE_LOG (
    LOG_ID                    NUMBER          NOT NULL,
    SESSION_TOKEN             VARCHAR2(50)    NOT NULL,
    REMOTE_PC_ID              NUMBER          NOT NULL,
    USER_ACCOUNT              VARCHAR2(200)   NOT NULL,
    CLIENT_PC                 VARCHAR2(100)   NOT NULL,
    MSTSC_PROCESS_ID          NUMBER,
    REQUESTED_AT              TIMESTAMP       NOT NULL,
    CONFIRMED_AT              TIMESTAMP,
    ENDED_AT                  TIMESTAMP,
    LAST_HEARTBEAT_AT         TIMESTAMP,
    SESSION_STATUS            VARCHAR2(30)    NOT NULL,
    START_SOURCE              VARCHAR2(50),
    END_SOURCE                VARCHAR2(50),
    RESULT_MESSAGE            VARCHAR2(1000),
    CREATED_AT                TIMESTAMP       NOT NULL,
    UPDATED_AT                TIMESTAMP       NOT NULL,
    CONSTRAINT PK_GBC_RDP_USAGE_LOG PRIMARY KEY (LOG_ID),
    CONSTRAINT UK_GBC_RDP_USAGE_TOKEN UNIQUE (SESSION_TOKEN),
    CONSTRAINT FK_GBC_RDP_USAGE_PC FOREIGN KEY (REMOTE_PC_ID)
        REFERENCES GBC_REMOTE_PC (REMOTE_PC_ID),
    CONSTRAINT CK_GBC_RDP_USAGE_STATUS CHECK (
        SESSION_STATUS IN ('CONNECTING', 'IN_USE', 'ENDED', 'CANCELLED', 'FAILED', 'CHECK_REQUIRED')
    )
);

CREATE INDEX IX_GBC_RDP_USAGE_PC ON GBC_RDP_USAGE_LOG (REMOTE_PC_ID);
CREATE INDEX IX_GBC_REMOTE_PC_STATUS ON GBC_REMOTE_PC (CURRENT_STATUS);

-- 4) 초기 데이터: KEB-7VY98V3
INSERT INTO GBC_REMOTE_PC (
    REMOTE_PC_ID,
    COMPUTER_NAME,
    IP_ADDRESS,
    DISPLAY_NAME,
    CURRENT_STATUS,
    UPDATED_AT,
    VERSION_NO,
    IS_ACTIVE
) VALUES (
    SEQ_GBC_REMOTE_PC.NEXTVAL,
    'KEB-7VY98V3',
    '172.16.49.61',
    'KEB-7VY98V3',
    'AVAILABLE',
    SYSTIMESTAMP,
    0,
    'Y'
);

COMMIT;

-- 5) 앱 계정에 부여할 권한 예시 (스키마/계정명은 DBA가 결정)
-- GRANT SELECT, INSERT, UPDATE ON GBC_REMOTE_PC TO <APP_USER>;
-- GRANT SELECT, INSERT, UPDATE ON GBC_RDP_USAGE_LOG TO <APP_USER>;
-- GRANT SELECT ON SEQ_GBC_REMOTE_PC TO <APP_USER>;
-- GRANT SELECT ON SEQ_GBC_RDP_USAGE_LOG TO <APP_USER>;
-- (필요 시) CREATE SYNONYM GBC_REMOTE_PC FOR <OWNER>.GBC_REMOTE_PC;
-- (필요 시) CREATE SYNONYM GBC_RDP_USAGE_LOG FOR <OWNER>.GBC_RDP_USAGE_LOG;
-- (필요 시) CREATE SYNONYM SEQ_GBC_REMOTE_PC FOR <OWNER>.SEQ_GBC_REMOTE_PC;
-- (필요 시) CREATE SYNONYM SEQ_GBC_RDP_USAGE_LOG FOR <OWNER>.SEQ_GBC_RDP_USAGE_LOG;
