-- ============================================================
-- GBC Work Hub — 업무기록 (MSDWHTKD 계열)
-- 마스터: XSUP.MSDWHTKD (원격 PC 현재 상태 — 변경하지 않음)
-- 본 DDL: MSDWHTKD_WRK / _PRJ / _SRC 만 추가
-- DBA 실행용. 앱에서 자동 실행하지 않음.
-- ============================================================
-- 모델:
--   1건 업무기록 = MSDWHTKD_WRK 1행
--   Project     = MSDWHTKD_WRK_PRJ N행
--   Source      = MSDWHTKD_WRK_SRC N행
-- 저장 시 자식은 DELETE 후 재INSERT.
-- ============================================================

-- 1) Sequences
CREATE SEQUENCE XSUP.SEQ_MSDWHTKD_WRK
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

CREATE SEQUENCE XSUP.SEQ_MSDWHTKD_WRK_PRJ
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

CREATE SEQUENCE XSUP.SEQ_MSDWHTKD_WRK_SRC
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

-- 2) 헤더
CREATE TABLE XSUP.MSDWHTKD_WRK (
    LOG_ID                  NUMBER            NOT NULL,
    CLIENT_KEY              VARCHAR2(100),
    SITE_CD                 VARCHAR2(20),
    WRITE_STATUS            VARCHAR2(20)      NOT NULL,
    TICKET_NO               VARCHAR2(100),
    TICKET_CONTENTS         VARCHAR2(2000),
    MENU_NM                 VARCHAR2(200),
    PC_NM                   VARCHAR2(100),
    PERSON_IN_CHARGE        VARCHAR2(200),
    LOCAL_PC_IP             VARCHAR2(50),
    START_DT                TIMESTAMP,
    END_DT                  TIMESTAMP,
    DEPLOY_STATUS           VARCHAR2(50),
    DEPLOY_DT               TIMESTAMP,
    WORK_COMMENT            VARCHAR2(2000),
    CHANGESET_ID            NUMBER            DEFAULT 0,
    TFS_COMMENT             VARCHAR2(2000),
    TFS_AUTHOR              VARCHAR2(200),
    AUTHOR_NM               VARCHAR2(200),
    CHECKED_IN_AT           TIMESTAMP,
    CHANGED_FILE_COUNT      NUMBER            DEFAULT 0,
    NEEDS_TICKET_REVIEW     CHAR(1)           DEFAULT 'Y' NOT NULL,
    CREATED_AT              TIMESTAMP         DEFAULT SYSTIMESTAMP NOT NULL,
    UPDT_DTM                TIMESTAMP         DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_MSDWHTKD_WRK PRIMARY KEY (LOG_ID),
    CONSTRAINT CK_MSDWHTKD_WRK_STS CHECK (WRITE_STATUS IN ('DRAFT', 'COMPLETED')),
    CONSTRAINT CK_MSDWHTKD_WRK_REV CHECK (NEEDS_TICKET_REVIEW IN ('Y', 'N'))
);

CREATE INDEX IX_MSDWHTKD_WRK_STATUS ON XSUP.MSDWHTKD_WRK (WRITE_STATUS);
CREATE INDEX IX_MSDWHTKD_WRK_SITE ON XSUP.MSDWHTKD_WRK (SITE_CD);
CREATE INDEX IX_MSDWHTKD_WRK_CS ON XSUP.MSDWHTKD_WRK (CHANGESET_ID);
CREATE INDEX IX_MSDWHTKD_WRK_UPDT ON XSUP.MSDWHTKD_WRK (UPDT_DTM);
CREATE INDEX IX_MSDWHTKD_WRK_IP ON XSUP.MSDWHTKD_WRK (LOCAL_PC_IP);

-- 3) Project
CREATE TABLE XSUP.MSDWHTKD_WRK_PRJ (
    PRJ_ID                  NUMBER            NOT NULL,
    LOG_ID                  NUMBER            NOT NULL,
    TYPE_NM                 VARCHAR2(100),
    CATEGORY_NM             VARCHAR2(100),
    PROJECT_NM              VARCHAR2(200),
    SOURCE_ORIGIN           VARCHAR2(50),
    DEPLOY_STATUS           VARCHAR2(50),
    DEPLOY_DT               TIMESTAMP,
    WORK_COMMENT            VARCHAR2(2000),
    SORT_ORD                NUMBER            DEFAULT 0 NOT NULL,
    CREATED_AT              TIMESTAMP         DEFAULT SYSTIMESTAMP NOT NULL,
    UPDT_DTM                TIMESTAMP         DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_MSDWHTKD_WRK_PRJ PRIMARY KEY (PRJ_ID),
    CONSTRAINT FK_MSDWHTKD_WRK_PRJ_LOG FOREIGN KEY (LOG_ID)
        REFERENCES XSUP.MSDWHTKD_WRK (LOG_ID) ON DELETE CASCADE
);

CREATE INDEX IX_MSDWHTKD_WRK_PRJ_LOG ON XSUP.MSDWHTKD_WRK_PRJ (LOG_ID);

-- 4) Source
CREATE TABLE XSUP.MSDWHTKD_WRK_SRC (
    SRC_ID                  NUMBER            NOT NULL,
    LOG_ID                  NUMBER            NOT NULL,
    PRJ_ID                  NUMBER,
    FILE_NM                 VARCHAR2(2000),
    ORIGINAL_PATH           VARCHAR2(2000),
    CHANGE_TYPE             VARCHAR2(50),
    CHANGE_DETAIL           VARCHAR2(1000),
    TYPE_NM                 VARCHAR2(100),
    CATEGORY_NM             VARCHAR2(100),
    PROJECT_NM              VARCHAR2(200),
    SOURCE_ORIGIN           VARCHAR2(50),
    APPLIED_RULE_CD         VARCHAR2(100),
    IS_AUTO_CLASSIFIED      CHAR(1)           DEFAULT 'N' NOT NULL,
    NEEDS_REVIEW            CHAR(1)           DEFAULT 'N' NOT NULL,
    REVIEW_REASON           VARCHAR2(500),
    SORT_ORD                NUMBER            DEFAULT 0 NOT NULL,
    CREATED_AT              TIMESTAMP         DEFAULT SYSTIMESTAMP NOT NULL,
    UPDT_DTM                TIMESTAMP         DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_MSDWHTKD_WRK_SRC PRIMARY KEY (SRC_ID),
    CONSTRAINT FK_MSDWHTKD_WRK_SRC_LOG FOREIGN KEY (LOG_ID)
        REFERENCES XSUP.MSDWHTKD_WRK (LOG_ID) ON DELETE CASCADE,
    CONSTRAINT FK_MSDWHTKD_WRK_SRC_PRJ FOREIGN KEY (PRJ_ID)
        REFERENCES XSUP.MSDWHTKD_WRK_PRJ (PRJ_ID) ON DELETE SET NULL,
    CONSTRAINT CK_MSDWHTKD_WRK_SRC_AUTO CHECK (IS_AUTO_CLASSIFIED IN ('Y', 'N')),
    CONSTRAINT CK_MSDWHTKD_WRK_SRC_REV CHECK (NEEDS_REVIEW IN ('Y', 'N'))
);

CREATE INDEX IX_MSDWHTKD_WRK_SRC_LOG ON XSUP.MSDWHTKD_WRK_SRC (LOG_ID);
CREATE INDEX IX_MSDWHTKD_WRK_SRC_PRJ ON XSUP.MSDWHTKD_WRK_SRC (PRJ_ID);

-- 5) 권한 (앱 계정명으로 바꿔서 실행)
-- GRANT SELECT, INSERT, UPDATE, DELETE ON XSUP.MSDWHTKD_WRK TO <APP_USER>;
-- GRANT SELECT, INSERT, UPDATE, DELETE ON XSUP.MSDWHTKD_WRK_PRJ TO <APP_USER>;
-- GRANT SELECT, INSERT, UPDATE, DELETE ON XSUP.MSDWHTKD_WRK_SRC TO <APP_USER>;
-- GRANT SELECT ON XSUP.SEQ_MSDWHTKD_WRK TO <APP_USER>;
-- GRANT SELECT ON XSUP.SEQ_MSDWHTKD_WRK_PRJ TO <APP_USER>;
-- GRANT SELECT ON XSUP.SEQ_MSDWHTKD_WRK_SRC TO <APP_USER>;

-- 확인:
-- SELECT * FROM XSUP.MSDWHTKD_WRK ORDER BY LOG_ID DESC;
-- SELECT * FROM XSUP.MSDWHTKD_WRK_PRJ WHERE LOG_ID = :id;
-- SELECT * FROM XSUP.MSDWHTKD_WRK_SRC WHERE LOG_ID = :id;
