-- 업무기록 사이트 구분 (AURORA / RC 등)
-- 기존 행은 AURORA 로 채움 (필요 시 수정)

ALTER TABLE XSUP.MSDWHTKD_WRK ADD (
    SITE_CD VARCHAR2(20)
);

UPDATE XSUP.MSDWHTKD_WRK
   SET SITE_CD = 'AURORA'
 WHERE SITE_CD IS NULL;

CREATE INDEX IX_MSDWHTKD_WRK_SITE ON XSUP.MSDWHTKD_WRK (SITE_CD);

-- 확인:
-- SELECT SITE_CD, COUNT(*) FROM XSUP.MSDWHTKD_WRK GROUP BY SITE_CD;
