-- 업무기록에 등록된 Changeset 레지스트리
-- 세션 구간 0건 → 오늘 체크인 폴백 시 "이미 등록된 CS" 판별용
-- DBA 계정으로 실행

CREATE SEQUENCE XSUP.SEQ_MSDWHTKD_WRK_CS
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

CREATE TABLE XSUP.MSDWHTKD_WRK_CS (
    CS_ROW_ID               NUMBER            NOT NULL,
    LOG_ID                  NUMBER            NOT NULL,
    CHANGESET_ID            NUMBER            NOT NULL,
    SITE_CD                 VARCHAR2(20),
    CHECKED_IN_AT           TIMESTAMP,
    CREATED_AT              TIMESTAMP         DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_MSDWHTKD_WRK_CS PRIMARY KEY (CS_ROW_ID),
    CONSTRAINT FK_MSDWHTKD_WRK_CS_LOG FOREIGN KEY (LOG_ID)
        REFERENCES XSUP.MSDWHTKD_WRK (LOG_ID) ON DELETE CASCADE,
    CONSTRAINT UQ_MSDWHTKD_WRK_CS UNIQUE (SITE_CD, CHANGESET_ID)
);

CREATE INDEX IX_MSDWHTKD_WRK_CS_LOG ON XSUP.MSDWHTKD_WRK_CS (LOG_ID);
CREATE INDEX IX_MSDWHTKD_WRK_CS_CS ON XSUP.MSDWHTKD_WRK_CS (CHANGESET_ID);

-- 기존 헤더 CHANGESET_ID 백필 (사이트+CS 중복 시 최신 LOG 1건만)
INSERT INTO XSUP.MSDWHTKD_WRK_CS (CS_ROW_ID, LOG_ID, CHANGESET_ID, SITE_CD, CHECKED_IN_AT, CREATED_AT)
SELECT XSUP.SEQ_MSDWHTKD_WRK_CS.NEXTVAL,
       src.LOG_ID,
       src.CHANGESET_ID,
       src.SITE_CD,
       src.CHECKED_IN_AT,
       SYSTIMESTAMP
  FROM (
        SELECT w.LOG_ID,
               w.CHANGESET_ID,
               NVL(w.SITE_CD, 'AURORA') AS SITE_CD,
               w.CHECKED_IN_AT,
               ROW_NUMBER() OVER (
                   PARTITION BY NVL(w.SITE_CD, 'AURORA'), w.CHANGESET_ID
                   ORDER BY w.UPDT_DTM DESC NULLS LAST, w.LOG_ID DESC
               ) AS RN
          FROM XSUP.MSDWHTKD_WRK w
         WHERE w.CHANGESET_ID IS NOT NULL
           AND w.CHANGESET_ID > 0
       ) src
 WHERE src.RN = 1
   AND NOT EXISTS (
         SELECT 1
           FROM XSUP.MSDWHTKD_WRK_CS c
          WHERE c.SITE_CD = src.SITE_CD
            AND c.CHANGESET_ID = src.CHANGESET_ID
       );

-- 권한 (앱 계정명으로 바꿔서 실행)
-- GRANT SELECT, INSERT, UPDATE, DELETE ON XSUP.MSDWHTKD_WRK_CS TO <APP_USER>;
-- GRANT SELECT ON XSUP.SEQ_MSDWHTKD_WRK_CS TO <APP_USER>;

-- 확인:
-- SELECT * FROM XSUP.MSDWHTKD_WRK_CS ORDER BY CS_ROW_ID DESC;
