-- 원격 PC 마스터(MSDWHTKD)에 사이트 구분 추가
-- App.config SiteCode (AURORA / RC …) 와 동일 값 사용

ALTER TABLE XSUP.MSDWHTKD ADD (
    SITE_CD VARCHAR2(20)
);

-- 기존 데이터 추정 채움 (필요 시 수동 수정)
UPDATE XSUP.MSDWHTKD
   SET SITE_CD = 'AURORA'
 WHERE SITE_CD IS NULL
   AND REGEXP_LIKE(REMOTE_ACCS_IP_ADDR, '^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+$');

UPDATE XSUP.MSDWHTKD
   SET SITE_CD = 'RC'
 WHERE SITE_CD IS NULL
   AND (REMOTE_ACCS_IP_ADDR LIKE 'HO-%'
        OR UPPER(REMOTE_PC_NM) LIKE '%BCARE%'
        OR UPPER(REMOTE_ACCS_IP_ADDR) LIKE '%BCARE%');

CREATE INDEX IX_MSDWHTKD_SITE ON XSUP.MSDWHTKD (SITE_CD);

-- 확인
-- SELECT SITE_CD, REMOTE_ACCS_IP_ADDR, REMOTE_PC_NM, ACCS_STS_CD
--   FROM XSUP.MSDWHTKD
--  ORDER BY SITE_CD, REMOTE_ACCS_IP_ADDR;
