-- CMC PC: P-BCTECH1 (ManageEngine PMP 웹 RDP)
-- App.config: CMC.Host = AutoLogon URL, CMC.PcNames = P-BCTECH1
-- 점유 키 = PC명 (REMOTE_ACCS_IP_ADDR 에 IP 대신 PC명)

-- SITE_CD 컬럼이 없으면 먼저 07_ALTER_MSDWHTKD_SITE_CD.sql 실행

MERGE INTO XSUP.MSDWHTKD t
USING (
    SELECT
        'P-BCTECH1' AS REMOTE_ACCS_IP_ADDR,
        'P-BCTECH1' AS REMOTE_PC_NM,
        'CMC'       AS SITE_CD
    FROM DUAL
) s
ON (t.REMOTE_ACCS_IP_ADDR = s.REMOTE_ACCS_IP_ADDR)
WHEN NOT MATCHED THEN
    INSERT (REMOTE_ACCS_IP_ADDR, REMOTE_PC_NM, SITE_CD, ACCS_STS_CD, UPDT_DTM)
    VALUES (s.REMOTE_ACCS_IP_ADDR, s.REMOTE_PC_NM, s.SITE_CD, 'AVAILABLE', SYSTIMESTAMP)
WHEN MATCHED THEN
    UPDATE SET
        t.REMOTE_PC_NM = s.REMOTE_PC_NM,
        t.SITE_CD = s.SITE_CD,
        t.UPDT_DTM = SYSTIMESTAMP;

COMMIT;

-- 확인
-- SELECT REMOTE_ACCS_IP_ADDR, REMOTE_PC_NM, SITE_CD, ACCS_STS_CD
--   FROM XSUP.MSDWHTKD
--  WHERE REMOTE_ACCS_IP_ADDR = 'P-BCTECH1';
