-- RC PC: HO-01-HIS-11 / HO-BESTCARE-06 (게시 RDP)
-- App.config: RC.PcNames 에 동일 PC명, RC.{PcName}.Host = IP
-- 점유 키 = PC명 (REMOTE_ACCS_IP_ADDR 에 IP 대신 PC명)
--   HO-01-HIS-11    = 10.80.25.66
--   HO-BESTCARE-06  = 10.80.25.64

-- SITE_CD 컬럼이 없으면 먼저 07_ALTER_MSDWHTKD_SITE_CD.sql 실행

MERGE INTO XSUP.MSDWHTKD t
USING (
    SELECT 'HO-01-HIS-11' AS REMOTE_ACCS_IP_ADDR, 'HO-01-HIS-11' AS REMOTE_PC_NM, 'RC' AS SITE_CD FROM DUAL
    UNION ALL
    SELECT 'HO-BESTCARE-06' AS REMOTE_ACCS_IP_ADDR, 'HO-BESTCARE-06' AS REMOTE_PC_NM, 'RC' AS SITE_CD FROM DUAL
) s
ON (t.REMOTE_ACCS_IP_ADDR = s.REMOTE_ACCS_IP_ADDR)
WHEN NOT MATCHED THEN
    INSERT (REMOTE_ACCS_IP_ADDR, REMOTE_PC_NM, SITE_CD, ACCS_STS_CD, UPDT_DTM)
    VALUES (s.REMOTE_ACCS_IP_ADDR, s.REMOTE_PC_NM, s.SITE_CD, 'AVAILABLE', SYSTIMESTAMP)
WHEN MATCHED THEN
    UPDATE SET
        t.REMOTE_PC_NM = s.REMOTE_PC_NM,
        t.SITE_CD = s.SITE_CD,
        t.UPDT_DTM = SYSTIMESTAMP;

COMMIT;

-- 확인
-- SELECT REMOTE_ACCS_IP_ADDR, REMOTE_PC_NM, SITE_CD, ACCS_STS_CD
--   FROM XSUP.MSDWHTKD
--  WHERE REMOTE_ACCS_IP_ADDR IN ('HO-01-HIS-11', 'HO-BESTCARE-06');
