-- ============================================================
-- GBC Work Hub — 사용자 마스터 / 원격 PC 이름↔IP 별명
-- DBA 실행용. 앱에서 CREATE/ALTER 하지 않음.
-- 점유 상태(MSDWHTKD)와 별개. CMC/RC 점유 키는 PC명 그대로.
-- ============================================================

CREATE SEQUENCE XSUP.SEQ_MSDWHTKD_USR
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

CREATE SEQUENCE XSUP.SEQ_MSDWHTKD_PCMAP
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

-- 이 Windows PC 한 줄. 점유명·소속 디렉터리 (로그인 계정 아님)
CREATE TABLE XSUP.MSDWHTKD_USR (
    USR_ID          NUMBER            NOT NULL,
    USER_NM         VARCHAR2(200)     NOT NULL,
    TEAM_NM         VARCHAR2(100),
    LOCAL_PC_NM     VARCHAR2(100)     NOT NULL,
    LOCAL_PC_IP     VARCHAR2(50),
    WIN_ACCOUNT     VARCHAR2(200),
    CREATED_AT      TIMESTAMP         DEFAULT SYSTIMESTAMP NOT NULL,
    UPDT_DTM        TIMESTAMP         DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_MSDWHTKD_USR PRIMARY KEY (USR_ID),
    CONSTRAINT UK_MSDWHTKD_USR_PC UNIQUE (LOCAL_PC_NM)
);

CREATE INDEX IX_MSDWHTKD_USR_NM ON XSUP.MSDWHTKD_USR (USER_NM);
CREATE INDEX IX_MSDWHTKD_USR_TEAM ON XSUP.MSDWHTKD_USR (TEAM_NM);

-- 사이트별 원격 PC명 ↔ IP ↔ 점유 키
CREATE TABLE XSUP.MSDWHTKD_PCMAP (
    MAP_ID          NUMBER            NOT NULL,
    SITE_CD         VARCHAR2(20)      NOT NULL,
    PC_NM           VARCHAR2(100)     NOT NULL,
    PC_IP           VARCHAR2(50),
    SHARE_KEY       VARCHAR2(100),
    TEAM_NM         VARCHAR2(100),
    PC_DOMAIN       VARCHAR2(500),
    PC_NOTE         VARCHAR2(4000),
    PC_COMMENT      VARCHAR2(2000),
    UPDT_DTM        TIMESTAMP         DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_MSDWHTKD_PCMAP PRIMARY KEY (MAP_ID),
    CONSTRAINT UK_MSDWHTKD_PCMAP_NM UNIQUE (SITE_CD, PC_NM)
);

CREATE INDEX IX_MSDWHTKD_PCMAP_IP ON XSUP.MSDWHTKD_PCMAP (SITE_CD, PC_IP);
CREATE INDEX IX_MSDWHTKD_PCMAP_KEY ON XSUP.MSDWHTKD_PCMAP (SHARE_KEY);
CREATE INDEX IX_MSDWHTKD_PCMAP_TEAM ON XSUP.MSDWHTKD_PCMAP (SITE_CD, TEAM_NM);

-- GRANT SELECT, INSERT, UPDATE ON XSUP.MSDWHTKD_USR TO <APP_USER>;
-- GRANT SELECT ON XSUP.SEQ_MSDWHTKD_USR TO <APP_USER>;
-- GRANT SELECT, INSERT, UPDATE ON XSUP.MSDWHTKD_PCMAP TO <APP_USER>;
-- GRANT SELECT ON XSUP.SEQ_MSDWHTKD_PCMAP TO <APP_USER>;

MERGE INTO XSUP.MSDWHTKD_PCMAP t
USING (
    SELECT 'CMC' AS SITE_CD, 'P-BCTECH1' AS PC_NM, '10.230.35.245' AS PC_IP, 'P-BCTECH1' AS SHARE_KEY FROM DUAL
    UNION ALL
    SELECT 'CMC', 'P-BCTECH2', '10.230.35.246', 'P-BCTECH2' FROM DUAL
    UNION ALL
    SELECT 'RC', 'HO-01-HIS-11', '10.80.25.66', 'HO-01-HIS-11' FROM DUAL
    UNION ALL
    SELECT 'RC', 'HO-BESTCARE-06', '10.80.25.64', 'HO-BESTCARE-06' FROM DUAL
    UNION ALL
    SELECT 'RC', 'HO-BCARE-07', '10.80.22.73', 'HO-BCARE-07' FROM DUAL
    UNION ALL
    SELECT 'AURORA', 'KEB-3VNZVP2', '172.16.49.59', '172.16.49.59' FROM DUAL
    UNION ALL
    SELECT 'AURORA', 'KEB-7VY98V3', '172.16.49.61', '172.16.49.61' FROM DUAL
    UNION ALL
    SELECT 'AURORA', 'KEB-DRY98V3', '172.16.49.56', '172.16.49.56' FROM DUAL
    UNION ALL
    SELECT 'AURORA', 'KEB-3TYYVP2', '172.16.49.57', '172.16.49.57' FROM DUAL
    UNION ALL
    SELECT 'AURORA', 'KEB-505F8R2', '172.16.49.58', '172.16.49.58' FROM DUAL
    UNION ALL
    SELECT 'AURORA', 'KEB-71V73Q3', '172.16.49.53', '172.16.49.53' FROM DUAL
) s
ON (UPPER(TRIM(t.SITE_CD)) = UPPER(TRIM(s.SITE_CD))
    AND UPPER(TRIM(t.PC_NM)) = UPPER(TRIM(s.PC_NM)))
WHEN NOT MATCHED THEN
    INSERT (MAP_ID, SITE_CD, PC_NM, PC_IP, SHARE_KEY, UPDT_DTM)
    VALUES (XSUP.SEQ_MSDWHTKD_PCMAP.NEXTVAL, s.SITE_CD, s.PC_NM, s.PC_IP, s.SHARE_KEY, SYSTIMESTAMP)
WHEN MATCHED THEN
    UPDATE SET
        t.PC_IP = NVL(s.PC_IP, t.PC_IP),
        t.SHARE_KEY = NVL(s.SHARE_KEY, t.SHARE_KEY),
        t.UPDT_DTM = SYSTIMESTAMP;

COMMIT;

-- 확인
-- SELECT * FROM XSUP.MSDWHTKD_USR ORDER BY UPDT_DTM DESC;
-- SELECT * FROM XSUP.MSDWHTKD_PCMAP ORDER BY SITE_CD, PC_NM;
