-- AURORA 진료간호 PC
-- KEB-3TYYVP2 (172.16.49.57)
-- KEB-505F8R2 (172.16.49.58)
-- KEB-71V73Q3 (172.16.49.53)
-- App.config: AURORA.PcNames + AURORA.{PC}.Host / Group=진료간호
-- 점유 키 = IP. 앱은 MSDWHTKD INSERT 안 함. 이 스크립트로 행을 넣어야 점유됨.

MERGE INTO XSUP.MSDWHTKD t
USING (
    SELECT '172.16.49.57' AS REMOTE_ACCS_IP_ADDR, 'KEB-3TYYVP2' AS REMOTE_PC_NM, 'AURORA' AS SITE_CD FROM DUAL
    UNION ALL
    SELECT '172.16.49.58', 'KEB-505F8R2', 'AURORA' FROM DUAL
    UNION ALL
    SELECT '172.16.49.53', 'KEB-71V73Q3', 'AURORA' FROM DUAL
) s
ON (t.REMOTE_ACCS_IP_ADDR = s.REMOTE_ACCS_IP_ADDR)
WHEN NOT MATCHED THEN
    INSERT (REMOTE_ACCS_IP_ADDR, REMOTE_PC_NM, SITE_CD, ACCS_STS_CD, UPDT_DTM)
    VALUES (s.REMOTE_ACCS_IP_ADDR, s.REMOTE_PC_NM, s.SITE_CD, 'AVAILABLE', SYSTIMESTAMP)
WHEN MATCHED THEN
    UPDATE SET
        t.REMOTE_PC_NM = s.REMOTE_PC_NM,
        t.SITE_CD = s.SITE_CD,
        t.UPDT_DTM = SYSTIMESTAMP;

COMMIT;

-- 확인
-- SELECT REMOTE_ACCS_IP_ADDR, REMOTE_PC_NM, SITE_CD, ACCS_STS_CD
--   FROM XSUP.MSDWHTKD
--  WHERE REMOTE_ACCS_IP_ADDR IN ('172.16.49.57', '172.16.49.58', '172.16.49.53');
