-- 원격 PC 소속(갤러리 그룹) + 신규 오로라 3대 등록
-- DBA 배포용. 앱에서 ALTER 하지 않음.
-- 컬럼/인덱스 있으면 건너뜀 (ORA-01430 / ORA-00955).
-- 기존 AURORA/RC/CMC + KEB-DRY98V3 = 진료지원
-- 오로라 진료간호 3대 = KEB-3TYYVP2 / 505F8R2 / 71V73Q3

BEGIN
    EXECUTE IMMEDIATE 'ALTER TABLE XSUP.MSDWHTKD_PCMAP ADD (TEAM_NM VARCHAR2(100))';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -1430 THEN RAISE; END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'CREATE INDEX IX_MSDWHTKD_PCMAP_TEAM ON XSUP.MSDWHTKD_PCMAP (SITE_CD, TEAM_NM)';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

MERGE INTO XSUP.MSDWHTKD_PCMAP t
USING (
    SELECT 'CMC' AS SITE_CD, 'P-BCTECH1' AS PC_NM, '10.230.35.245' AS PC_IP, 'P-BCTECH1' AS SHARE_KEY, '진료지원' AS TEAM_NM FROM DUAL
    UNION ALL
    SELECT 'CMC', 'P-BCTECH2', '10.230.35.246', 'P-BCTECH2', '진료지원' FROM DUAL
    UNION ALL
    SELECT 'RC', 'HO-BCARE-07', '10.80.22.73', 'HO-BCARE-07', '진료지원' FROM DUAL
    UNION ALL
    SELECT 'RC', 'HO-01-HIS-11', '10.80.25.66', 'HO-01-HIS-11', '진료지원' FROM DUAL
    UNION ALL
    SELECT 'RC', 'HO-BESTCARE-06', '10.80.25.64', 'HO-BESTCARE-06', '진료지원' FROM DUAL
    UNION ALL
    SELECT 'AURORA', 'KEB-3VNZVP2', '172.16.49.59', '172.16.49.59', '진료지원' FROM DUAL
    UNION ALL
    SELECT 'AURORA', 'KEB-7VY98V3', '172.16.49.61', '172.16.49.61', '진료지원' FROM DUAL
    UNION ALL
    SELECT 'AURORA', 'KEB-DRY98V3', '172.16.49.56', '172.16.49.56', '진료지원' FROM DUAL
    UNION ALL
    SELECT 'AURORA', 'KEB-3TYYVP2', '172.16.49.57', '172.16.49.57', '진료간호' FROM DUAL
    UNION ALL
    SELECT 'AURORA', 'KEB-505F8R2', '172.16.49.58', '172.16.49.58', '진료간호' FROM DUAL
    UNION ALL
    SELECT 'AURORA', 'KEB-71V73Q3', '172.16.49.53', '172.16.49.53', '진료간호' FROM DUAL
) s
ON (UPPER(TRIM(t.SITE_CD)) = UPPER(TRIM(s.SITE_CD))
    AND UPPER(TRIM(t.PC_NM)) = UPPER(TRIM(s.PC_NM)))
WHEN NOT MATCHED THEN
    INSERT (MAP_ID, SITE_CD, PC_NM, PC_IP, SHARE_KEY, TEAM_NM, UPDT_DTM)
    VALUES (XSUP.SEQ_MSDWHTKD_PCMAP.NEXTVAL, s.SITE_CD, s.PC_NM, s.PC_IP, s.SHARE_KEY, s.TEAM_NM, SYSTIMESTAMP)
WHEN MATCHED THEN
    UPDATE SET
        t.PC_IP = NVL(s.PC_IP, t.PC_IP),
        t.SHARE_KEY = NVL(s.SHARE_KEY, t.SHARE_KEY),
        t.TEAM_NM = s.TEAM_NM,
        t.UPDT_DTM = SYSTIMESTAMP;

COMMIT;

MERGE INTO XSUP.MSDWHTKD t
USING (
    SELECT '172.16.49.56' AS REMOTE_ACCS_IP_ADDR, 'KEB-DRY98V3' AS REMOTE_PC_NM, 'AURORA' AS SITE_CD FROM DUAL
) s
ON (t.REMOTE_ACCS_IP_ADDR = s.REMOTE_ACCS_IP_ADDR)
WHEN NOT MATCHED THEN
    INSERT (REMOTE_ACCS_IP_ADDR, REMOTE_PC_NM, SITE_CD, ACCS_STS_CD, UPDT_DTM)
    VALUES (s.REMOTE_ACCS_IP_ADDR, s.REMOTE_PC_NM, s.SITE_CD, 'AVAILABLE', SYSTIMESTAMP)
WHEN MATCHED THEN
    UPDATE SET
        t.REMOTE_PC_NM = s.REMOTE_PC_NM,
        t.SITE_CD = s.SITE_CD,
        t.UPDT_DTM = SYSTIMESTAMP;

COMMIT;

-- 확인
-- SELECT SITE_CD, PC_NM, PC_IP, TEAM_NM FROM XSUP.MSDWHTKD_PCMAP ORDER BY SITE_CD, TEAM_NM, PC_NM;
