-- ============================================================
-- MSDWHTKD_USR 로그인용 컬럼 (LOGIN_ID / PASSWORD_HASH / IS_ACTIVE)
-- DBA 실행용. 앱은 probe 후 없으면 비밀번호 DB 저장을 건너뜀.
-- 재실행 안전: 컬럼/인덱스 있으면 ORA-01430 / ORA-00955 무시.
-- ADMIN 계정: sql/21_ADMIN_USER_SEED.sql
-- ============================================================

-- ------------------------------------------------------------
-- 1) 먼저 확인 (3행 모두 EXISTS 이면 sql/20 본문은 안 돌려도 됨)
-- ------------------------------------------------------------
SELECT 'LOGIN_ID' AS OBJ_NAME,
       CASE WHEN COUNT(*) > 0 THEN 'EXISTS' ELSE 'MISSING' END AS STATUS
  FROM ALL_TAB_COLUMNS
 WHERE OWNER = 'XSUP' AND TABLE_NAME = 'MSDWHTKD_USR' AND COLUMN_NAME = 'LOGIN_ID'
UNION ALL
SELECT 'PASSWORD_HASH',
       CASE WHEN COUNT(*) > 0 THEN 'EXISTS' ELSE 'MISSING' END
  FROM ALL_TAB_COLUMNS
 WHERE OWNER = 'XSUP' AND TABLE_NAME = 'MSDWHTKD_USR' AND COLUMN_NAME = 'PASSWORD_HASH'
UNION ALL
SELECT 'IS_ACTIVE',
       CASE WHEN COUNT(*) > 0 THEN 'EXISTS' ELSE 'MISSING' END
  FROM ALL_TAB_COLUMNS
 WHERE OWNER = 'XSUP' AND TABLE_NAME = 'MSDWHTKD_USR' AND COLUMN_NAME = 'IS_ACTIVE'
UNION ALL
SELECT 'UX_MSDWHTKD_USR_LOGIN',
       CASE WHEN COUNT(*) > 0 THEN 'EXISTS' ELSE 'MISSING' END
  FROM ALL_INDEXES
 WHERE OWNER = 'XSUP' AND INDEX_NAME = 'UX_MSDWHTKD_USR_LOGIN';

-- ------------------------------------------------------------
-- 2) 아래는 MISSING 이 있을 때만 실행 (있어도 재실행 안전)
-- ------------------------------------------------------------

BEGIN
    EXECUTE IMMEDIATE 'ALTER TABLE XSUP.MSDWHTKD_USR ADD LOGIN_ID VARCHAR2(100)';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -1430 THEN RAISE; END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'ALTER TABLE XSUP.MSDWHTKD_USR ADD PASSWORD_HASH VARCHAR2(128)';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -1430 THEN RAISE; END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'ALTER TABLE XSUP.MSDWHTKD_USR ADD IS_ACTIVE CHAR(1) DEFAULT ''Y'' NOT NULL';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -1430 THEN RAISE; END IF;
END;
/

-- 기존 행: LOGIN_ID 비어 있으면 USER_NM 으로 채움
UPDATE XSUP.MSDWHTKD_USR
   SET LOGIN_ID = USER_NM
 WHERE LOGIN_ID IS NULL
   AND USER_NM IS NOT NULL;

BEGIN
    EXECUTE IMMEDIATE
        'CREATE UNIQUE INDEX UX_MSDWHTKD_USR_LOGIN ON XSUP.MSDWHTKD_USR (UPPER(TRIM(LOGIN_ID)))';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

COMMIT;

-- ------------------------------------------------------------
-- 3) 적용 후 재확인 (전부 EXISTS 이어야 함)
-- ------------------------------------------------------------
SELECT 'LOGIN_ID' AS OBJ_NAME,
       CASE WHEN COUNT(*) > 0 THEN 'EXISTS' ELSE 'MISSING' END AS STATUS
  FROM ALL_TAB_COLUMNS
 WHERE OWNER = 'XSUP' AND TABLE_NAME = 'MSDWHTKD_USR' AND COLUMN_NAME = 'LOGIN_ID'
UNION ALL
SELECT 'PASSWORD_HASH',
       CASE WHEN COUNT(*) > 0 THEN 'EXISTS' ELSE 'MISSING' END
  FROM ALL_TAB_COLUMNS
 WHERE OWNER = 'XSUP' AND TABLE_NAME = 'MSDWHTKD_USR' AND COLUMN_NAME = 'PASSWORD_HASH'
UNION ALL
SELECT 'IS_ACTIVE',
       CASE WHEN COUNT(*) > 0 THEN 'EXISTS' ELSE 'MISSING' END
  FROM ALL_TAB_COLUMNS
 WHERE OWNER = 'XSUP' AND TABLE_NAME = 'MSDWHTKD_USR' AND COLUMN_NAME = 'IS_ACTIVE'
UNION ALL
SELECT 'UX_MSDWHTKD_USR_LOGIN',
       CASE WHEN COUNT(*) > 0 THEN 'EXISTS' ELSE 'MISSING' END
  FROM ALL_INDEXES
 WHERE OWNER = 'XSUP' AND INDEX_NAME = 'UX_MSDWHTKD_USR_LOGIN';
