-- ============================================================
-- GBC Work Hub — 개선사항 요청 (버그/기능개선/기타)
-- 선행: sql/23_MSDWHTKD_USR_IDENTITY_FIX.sql (USR_ID를 FK로 참조)
-- DBA 실행용. 앱에서 CREATE/ALTER 하지 않음.
-- 모델: 요청 1건 = MSDWHTKD_REQ 1행, 댓글/반응/첨부는 REQ_ID 자식(개별 CRUD, delete-all-reinsert 아님)
-- ============================================================

CREATE SEQUENCE XSUP.SEQ_MSDWHTKD_REQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE XSUP.SEQ_MSDWHTKD_REQ_COMMENT START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE XSUP.SEQ_MSDWHTKD_REQ_ATTACH START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE TABLE XSUP.MSDWHTKD_REQ (
    REQ_ID              NUMBER          NOT NULL,
    REQUEST_TYPE        VARCHAR2(20)    NOT NULL,
    TITLE                VARCHAR2(200)   NOT NULL,
    DESCRIPTION          VARCHAR2(4000),
    REPRODUCTION_STEPS   VARCHAR2(4000),
    APP_VERSION          VARCHAR2(20),
    SITE_CD              VARCHAR2(20),
    PC_NM                VARCHAR2(100),
    USER_ID              NUMBER          NOT NULL,
    AUTHOR_NM            VARCHAR2(200)   NOT NULL,
    TEAM_NM              VARCHAR2(100),
    STATUS               VARCHAR2(20)    DEFAULT 'OPEN' NOT NULL,
    RESOLVED_VERSION     VARCHAR2(20),
    ADMIN_NOTE           VARCHAR2(2000),
    CREATED_AT           TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT           TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,
    RESOLVED_AT          TIMESTAMP,
    CONSTRAINT PK_MSDWHTKD_REQ PRIMARY KEY (REQ_ID),
    CONSTRAINT FK_MSDWHTKD_REQ_USER FOREIGN KEY (USER_ID)
        REFERENCES XSUP.MSDWHTKD_USR (USR_ID),
    CONSTRAINT CK_MSDWHTKD_REQ_TYPE CHECK (REQUEST_TYPE IN ('BUG','IMPROVEMENT','ETC')),
    CONSTRAINT CK_MSDWHTKD_REQ_STS  CHECK (STATUS IN ('OPEN','CHECKING','IN_PROGRESS','RESOLVED'))
);
CREATE INDEX IX_MSDWHTKD_REQ_STATUS  ON XSUP.MSDWHTKD_REQ (STATUS);
CREATE INDEX IX_MSDWHTKD_REQ_TYPE    ON XSUP.MSDWHTKD_REQ (REQUEST_TYPE);
CREATE INDEX IX_MSDWHTKD_REQ_SITE    ON XSUP.MSDWHTKD_REQ (SITE_CD);
CREATE INDEX IX_MSDWHTKD_REQ_CREATED ON XSUP.MSDWHTKD_REQ (CREATED_AT);
CREATE INDEX IX_MSDWHTKD_REQ_USER    ON XSUP.MSDWHTKD_REQ (USER_ID);

CREATE TABLE XSUP.MSDWHTKD_REQ_COMMENT (
    COMMENT_ID   NUMBER          NOT NULL,
    REQ_ID       NUMBER          NOT NULL,
    USER_ID      NUMBER          NOT NULL,
    AUTHOR_NM    VARCHAR2(200)   NOT NULL,
    COMMENT_TEXT VARCHAR2(2000)  NOT NULL,
    APP_VERSION  VARCHAR2(20),
    CREATED_AT   TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT   TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_MSDWHTKD_REQ_COMMENT PRIMARY KEY (COMMENT_ID),
    CONSTRAINT FK_MSDWHTKD_REQ_COMMENT_REQ FOREIGN KEY (REQ_ID)
        REFERENCES XSUP.MSDWHTKD_REQ (REQ_ID) ON DELETE CASCADE,
    CONSTRAINT FK_MSDWHTKD_REQ_COMMENT_USER FOREIGN KEY (USER_ID)
        REFERENCES XSUP.MSDWHTKD_USR (USR_ID)
);
CREATE INDEX IX_MSDWHTKD_REQ_COMMENT_REQ  ON XSUP.MSDWHTKD_REQ_COMMENT (REQ_ID);
CREATE INDEX IX_MSDWHTKD_REQ_COMMENT_USER ON XSUP.MSDWHTKD_REQ_COMMENT (USER_ID);

-- 1인 1반응: 복합 PK 자체가 유니크 제약 (REQ_ID+USER_ID)
CREATE TABLE XSUP.MSDWHTKD_REQ_REACTION (
    REQ_ID        NUMBER          NOT NULL,
    USER_ID       NUMBER          NOT NULL,
    REACTION_TYPE VARCHAR2(20)    NOT NULL,
    CREATED_AT    TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT    TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_MSDWHTKD_REQ_REACTION PRIMARY KEY (REQ_ID, USER_ID),
    CONSTRAINT FK_MSDWHTKD_REQ_REACTION_REQ FOREIGN KEY (REQ_ID)
        REFERENCES XSUP.MSDWHTKD_REQ (REQ_ID) ON DELETE CASCADE,
    CONSTRAINT FK_MSDWHTKD_REQ_REACTION_USER FOREIGN KEY (USER_ID)
        REFERENCES XSUP.MSDWHTKD_USR (USR_ID),
    CONSTRAINT CK_MSDWHTKD_REQ_REACTION_TYPE CHECK (REACTION_TYPE IN ('REPRODUCED','NOT_REPRODUCED'))
);

CREATE TABLE XSUP.MSDWHTKD_REQ_ATTACH (
    ATTACH_ID  NUMBER          NOT NULL,
    REQ_ID     NUMBER          NOT NULL,
    FILE_NM    VARCHAR2(260)   NOT NULL,
    FILE_EXT   VARCHAR2(10)    NOT NULL,
    FILE_SIZE  NUMBER,
    FILE_DATA  BLOB            NOT NULL,
    CREATED_AT TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_MSDWHTKD_REQ_ATTACH PRIMARY KEY (ATTACH_ID),
    CONSTRAINT FK_MSDWHTKD_REQ_ATTACH_REQ FOREIGN KEY (REQ_ID)
        REFERENCES XSUP.MSDWHTKD_REQ (REQ_ID) ON DELETE CASCADE,
    CONSTRAINT CK_MSDWHTKD_REQ_ATTACH_EXT CHECK (LOWER(FILE_EXT) IN ('png','jpg','jpeg'))
);
CREATE INDEX IX_MSDWHTKD_REQ_ATTACH_REQ ON XSUP.MSDWHTKD_REQ_ATTACH (REQ_ID);

-- 권한 (앱 계정명으로 바꿔서 실행)
-- GRANT SELECT, INSERT, UPDATE, DELETE ON XSUP.MSDWHTKD_REQ TO <APP_USER>;
-- GRANT SELECT, INSERT, UPDATE, DELETE ON XSUP.MSDWHTKD_REQ_COMMENT TO <APP_USER>;
-- GRANT SELECT, INSERT, UPDATE, DELETE ON XSUP.MSDWHTKD_REQ_REACTION TO <APP_USER>;
-- GRANT SELECT, INSERT, DELETE ON XSUP.MSDWHTKD_REQ_ATTACH TO <APP_USER>;
-- GRANT SELECT ON XSUP.SEQ_MSDWHTKD_REQ TO <APP_USER>;
-- GRANT SELECT ON XSUP.SEQ_MSDWHTKD_REQ_COMMENT TO <APP_USER>;
-- GRANT SELECT ON XSUP.SEQ_MSDWHTKD_REQ_ATTACH TO <APP_USER>;

-- 확인:
-- SELECT * FROM XSUP.MSDWHTKD_REQ ORDER BY REQ_ID DESC;
